services:
  bot:
    build: .
    command: python3 -O main.py
    container_name: ellie-bot
    depends_on:
      - db
    ports:
      - "59076:59076"
    restart: unless-stopped
    dns:
      - 76.76.2.2
      - 76.76.10.2

  db:
    container_name: ellie-db
    environment:
      - POSTGRES_DB=ellie
      - POSTGRES_PASSWORD=pN3PqpT86Nfr
      - POSTGRES_USER=ellie
    image: postgres:alpine
    expose:
      - "5432"
    restart: always
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
